package uiapi

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"math/big"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

func browserTestKey(t *testing.T) (*ecdsa.PrivateKey, BrowserPublicKey) {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	return key, publicTestKey(key)
}
func publicTestKey(key *ecdsa.PrivateKey) BrowserPublicKey {
	encoded, err := key.PublicKey.Bytes()
	if err != nil {
		panic(err)
	} // test keys are generated by ecdsa.GenerateKey
	return BrowserPublicKey{Kty: "EC", Crv: "P-256", X: base64.RawURLEncoding.EncodeToString(encoded[1:33]), Y: base64.RawURLEncoding.EncodeToString(encoded[33:])}
}

// Existing authentication tests can create sessions without pretending that
// a private key or a browser token is a persisted record.
func (a *authStore) newSession(origin string) (string, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return "", err
	}
	_, token, _, err := a.registerBrowser(origin, publicTestKey(key))
	return token, err
}

func restartSessionHarness(t *testing.T, h *harness) {
	t.Helper()
	opts := h.s.opts
	opts.Port = h.s.browserPort
	if err := h.s.Shutdown(context.Background()); err != nil {
		t.Fatal(err)
	}
	next, err := Start(opts)
	if err != nil {
		t.Fatal(err)
	}
	h.s = next
	h.local = unixClient(next.Endpoint().UnixSocket)
	t.Cleanup(func() { _ = next.Shutdown(context.Background()) })
}
func (h *harness) pairBrowserKey() (*ecdsa.PrivateKey, PairingExchange) {
	h.t.Helper()
	key, pub := browserTestKey(h.t)
	code := h.pairingCode("/")
	body, _ := json.Marshal(PairingExchangeRequest{Code: code.Code, PublicKey: pub})
	r, b := h.browserDo(req{method: http.MethodPost, path: "/api/v0/pairing/exchange", body: string(body), header: mutationHeaders(h.ownOrigin(), nil)})
	expect(h.t, r, b, 200, "")
	var paired PairingExchange
	if err := json.Unmarshal(b, &paired); err != nil {
		h.t.Fatal(err)
	}
	return key, paired
}
func (h *harness) proofChallenge(id string) SessionProofChallenge {
	h.t.Helper()
	body, _ := json.Marshal(SessionProofChallengeRequest{RegistrationID: id})
	r, b := h.browserDo(req{method: http.MethodPost, path: "/api/v0/pairing/session-proof", body: string(body), header: mutationHeaders(h.ownOrigin(), nil)})
	expect(h.t, r, b, 200, "")
	var challenge SessionProofChallenge
	if err := json.Unmarshal(b, &challenge); err != nil {
		h.t.Fatal(err)
	}
	return challenge
}
func signedProof(t *testing.T, key *ecdsa.PrivateKey, origin, id string, challenge SessionProofChallenge) SessionProofRequest {
	t.Helper()
	digest := sha256.Sum256([]byte(BrowserProofMessage(origin, id, challenge.Nonce, challenge.Timestamp)))
	r, s, err := ecdsa.Sign(rand.Reader, key, digest[:])
	if err != nil {
		t.Fatal(err)
	}
	sig := append(r.FillBytes(make([]byte, 32)), s.FillBytes(make([]byte, 32))...)
	return SessionProofRequest{RegistrationID: id, Nonce: challenge.Nonce, Timestamp: challenge.Timestamp, Signature: base64.RawURLEncoding.EncodeToString(sig)}
}
func (h *harness) submitProof(origin string, proof SessionProofRequest) (*http.Response, []byte) {
	body, _ := json.Marshal(proof)
	return h.browserDo(req{method: http.MethodPost, path: "/api/v0/pairing/session-proof/verify", body: string(body), header: mutationHeaders(origin, nil)})
}
func (h *harness) renewBrowser(key *ecdsa.PrivateKey, id string) SessionToken {
	h.t.Helper()
	proof := signedProof(h.t, key, h.ownOrigin(), id, h.proofChallenge(id))
	r, b := h.submitProof(h.ownOrigin(), proof)
	expect(h.t, r, b, 200, "")
	var token SessionToken
	if err := json.Unmarshal(b, &token); err != nil {
		h.t.Fatal(err)
	}
	return token
}
func (h *harness) expectBearer(token string, status int) {
	h.t.Helper()
	r, b := h.browserDo(req{path: "/api/v0/hello", header: map[string]string{"Authorization": "Bearer " + token}})
	code := ""
	if status == 401 {
		code = CodeUnauthenticated
	}
	expect(h.t, r, b, status, code)
}

func TestBrowserPublicKeysSurviveRestartAndRevocation(t *testing.T) {
	for _, route := range []string{"all", "origin-sessions", "origin"} {
		t.Run(route, func(t *testing.T) {
			h := newHarness(t)
			key, paired := h.pairBrowserKey()
			secondKey, second := h.pairBrowserKey()
			h.expectBearer(paired.Token, 200)
			restartSessionHarness(t, h)
			h.expectBearer(paired.Token, 401) // memory-only bearer dies with the process
			fresh := h.renewBrowser(key, paired.RegistrationID)
			h.expectBearer(fresh.Token, 200)
			other := h.renewBrowser(secondKey, second.RegistrationID)
			h.expectBearer(other.Token, 200)
			switch route {
			case "all":
				h.revokeSessions("")
			case "origin-sessions":
				h.revokeSessions("?origin=" + url.QueryEscape(h.ownOrigin()))
			case "origin":
				r, b := h.localDo(req{method: http.MethodPost, path: "/api/v0/origins", body: `{"origin":"` + h.ownOrigin() + `"}`})
				expect(t, r, b, 200, "")
				r, b = h.localDo(req{method: http.MethodDelete, path: "/api/v0/origins?origin=" + url.QueryEscape(h.ownOrigin())})
				expect(t, r, b, 200, "")
			}
			h.expectBearer(fresh.Token, 401)
			restartSessionHarness(t, h)
			for _, id := range []string{paired.RegistrationID, second.RegistrationID} {
				body, _ := json.Marshal(SessionProofChallengeRequest{RegistrationID: id})
				r, b := h.browserDo(req{method: "POST", path: "/api/v0/pairing/session-proof", body: string(body), header: mutationHeaders(h.ownOrigin(), nil)})
				expect(t, r, b, 401, CodeSessionProofInvalid)
			}
		})
	}
}

func TestBrowserProofReplayOriginTimestampAndExpiry(t *testing.T) {
	h := newHarness(t)
	key, paired := h.pairBrowserKey()
	proof := signedProof(t, key, h.ownOrigin(), paired.RegistrationID, h.proofChallenge(paired.RegistrationID))
	r, b := h.submitProof(h.ownOrigin(), proof)
	expect(t, r, b, 200, "")
	r, b = h.submitProof(h.ownOrigin(), proof)
	expect(t, r, b, 401, CodeSessionProofInvalid)
	for _, wrong := range []string{"signed-origin", "request-origin", "timestamp", "key", "expired"} {
		t.Run(wrong, func(t *testing.T) {
			challenge := h.proofChallenge(paired.RegistrationID)
			origin := h.ownOrigin()
			signOrigin := origin
			signKey := key
			if wrong == "signed-origin" {
				signOrigin = "http://localhost:" + h.browserPort()
			}
			if wrong == "key" {
				signKey, _ = browserTestKey(t)
			}
			proof := signedProof(t, signKey, signOrigin, paired.RegistrationID, challenge)
			if wrong == "request-origin" {
				origin = "http://localhost:" + h.browserPort()
			}
			if wrong == "timestamp" {
				proof.Timestamp++
			}
			if wrong == "expired" {
				h.clock.Advance(pairingCodeTTL)
			}
			r, b := h.submitProof(origin, proof)
			expect(t, r, b, 401, CodeSessionProofInvalid)
			r, b = h.submitProof(h.ownOrigin(), proof)
			expect(t, r, b, 401, CodeSessionProofInvalid)
		})
	}
	// Renewing a bearer leaves an already-open tab's short-lived token usable.
	old := h.renewBrowser(key, paired.RegistrationID)
	h.renewBrowser(key, paired.RegistrationID)
	h.expectBearer(old.Token, 200)
	h.clock.Advance(browserBearerTTL)
	h.expectBearer(old.Token, 401)
	h.expectBearer(h.renewBrowser(key, paired.RegistrationID).Token, 200)
}

func TestBrowserRegistrationSlidingExpiryAndAbsoluteCap(t *testing.T) {
	h := newHarness(t)
	key, paired := h.pairBrowserKey()
	created := h.clock.Now()
	for i := 0; i < 8; i++ {
		h.clock.Advance(20 * 24 * time.Hour)
		restartSessionHarness(t, h)
		h.expectBearer(h.renewBrowser(key, paired.RegistrationID).Token, 200)
	}
	h.clock.Advance(created.Add(sessionAbsoluteTTL).Sub(h.clock.Now()))
	restartSessionHarness(t, h)
	_, err := h.s.auth.issueBrowserProof(h.ownOrigin(), paired.RegistrationID)
	if err == nil {
		t.Fatal("absolute cap did not expire registration")
	}
	_, paired = h.pairBrowserKey()
	h.clock.Advance(sessionIdleTTL)
	restartSessionHarness(t, h)
	if _, err := h.s.auth.issueBrowserProof(h.ownOrigin(), paired.RegistrationID); err == nil {
		t.Fatal("idle expiry did not expire registration")
	}
}

func TestBrowserRegistrationStorePublicOnlyModeCorruptionAndMigration(t *testing.T) {
	h := newHarness(t)
	key, paired := h.pairBrowserKey()
	path := filepath.Join(Dir(h.state), sessionsFileName)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	privateBytes, err := key.Bytes()
	if err != nil {
		t.Fatal(err)
	}
	private := base64.RawURLEncoding.EncodeToString(privateBytes)
	if strings.Contains(string(data), paired.Token) || strings.Contains(string(data), hashToken(paired.Token)) || strings.Contains(string(data), private) || !strings.Contains(string(data), paired.RegistrationID) {
		t.Fatal("store contains bearer/private material or lacks public registration")
	}
	info, err := os.Stat(path)
	if err != nil || info.Mode().Perm() != 0600 {
		t.Fatalf("mode %v %v", info, err)
	}
	if err := os.Chmod(path, 0644); err != nil {
		t.Fatal(err)
	}
	restartSessionHarness(t, h)
	info, _ = os.Stat(path)
	if info.Mode().Perm() != 0600 {
		t.Fatal("copied file mode not tightened")
	}
	token := h.renewBrowser(key, paired.RegistrationID).Token
	if err := os.WriteFile(path, []byte(`{"version":1,"registrations":{"bad":{}}}`), 0600); err != nil {
		t.Fatal(err)
	}
	h.expectBearer(token, 401)
	opts := h.s.opts
	_ = h.s.Shutdown(context.Background())
	s, err := Start(opts)
	if s != nil {
		_ = s.Shutdown(context.Background())
		t.Fatal("corrupt store started server")
	}
	if err == nil || !strings.Contains(err.Error(), "public-key store") || !strings.Contains(err.Error(), "pair browsers again") {
		t.Fatalf("corruption message %v", err)
	}
	if err := os.WriteFile(path, []byte(`{"sessions":{"legacy-token-hash":{"origin":"http://localhost:7861"}}}`), 0600); err != nil {
		t.Fatal(err)
	}
	next, err := Start(opts)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = next.Shutdown(context.Background()) })
	data, _ = os.ReadFile(path)
	if strings.Contains(string(data), "legacy-token-hash") || strings.Contains(string(data), "\"sessions\"") {
		t.Fatal("legacy bearer store retained")
	}
}

func TestBrowserStoreCachedReadsThrottledTouchesAndExternalRevoke(t *testing.T) {
	h := newHarness(t)
	_, paired := h.pairBrowserKey()
	path := filepath.Join(Dir(h.state), sessionsFileName)
	before, _ := os.Stat(path)
	for i := 0; i < 10; i++ {
		h.clock.Advance(5 * time.Second)
		h.expectBearer(paired.Token, 200)
	}
	same, _ := os.Stat(path)
	if !os.SameFile(before, same) {
		t.Fatal("requests within one minute rewrote store")
	}
	h.clock.Advance(10 * time.Second)
	h.expectBearer(paired.Token, 200)
	after, _ := os.Stat(path)
	if os.SameFile(before, after) {
		t.Fatal("one-minute touch was not persisted")
	}
	// Unknown tokens bypass even the file-change check and cannot encounter this bad path.
	h.s.auth.mu.Lock()
	oldPath := h.s.auth.sessionPath
	h.s.auth.sessionPath = "/no/such/parent/sessions.json"
	h.s.auth.mu.Unlock()
	h.expectBearer("unknown-token", 401)
	h.s.auth.mu.Lock()
	if h.s.auth.storeErr != nil {
		t.Fatal("unknown token read the store")
	}
	h.s.auth.sessionPath = oldPath
	h.s.auth.mu.Unlock()
	other := newAuthStore(h.clock.Now)
	other.sessionPath = path
	if _, err := other.revokeSessions(""); err != nil {
		t.Fatal(err)
	}
	h.expectBearer(paired.Token, 401)
	if _, err := h.s.auth.issueBrowserProof(h.ownOrigin(), paired.RegistrationID); err == nil {
		t.Fatal("cached index ignored external revocation")
	}
}

func TestSessionStoreConcurrentWritersCannotResurrectRevocation(t *testing.T) {
	clock := &fakeClock{now: time.Now().UTC()}
	path := filepath.Join(t.TempDir(), sessionsFileName)
	stores := []*authStore{newAuthStore(clock.Now), newAuthStore(clock.Now)}
	for _, s := range stores {
		s.sessionPath = path
	}
	token, err := stores[0].newSession("http://localhost:7861")
	if err != nil {
		t.Fatal(err)
	}
	var wg sync.WaitGroup
	for _, s := range stores {
		wg.Add(1)
		go func(a *authStore) {
			defer wg.Done()
			for i := 0; i < 10; i++ {
				if _, err := a.newSession("http://localhost:7861"); err != nil {
					t.Error(err)
				}
			}
		}(s)
	}
	wg.Wait()
	all, err := readSessions(path)
	if err != nil || len(all) != 21 {
		t.Fatalf("lost concurrent writers %d %v", len(all), err)
	}
	if _, err := stores[1].revokeSessions(""); err != nil {
		t.Fatal(err)
	}
	if _, err := stores[0].newSession("http://localhost:7861"); err != nil {
		t.Fatal(err)
	}
	if _, _, ok := stores[0].lookupSession(token); ok {
		t.Fatal("stale writer resurrected revoked registration")
	}
	all, err = readSessions(path)
	if err != nil || len(all) != 1 {
		t.Fatalf("atomic store %d %v", len(all), err)
	}
}

func TestBrowserPublicKeyValidationDoesNotConsumeCode(t *testing.T) {
	h := newHarness(t)
	_, valid := browserTestKey(t)
	for _, kind := range []string{"missing", "private", "curve", "point", "encoding"} {
		t.Run(kind, func(t *testing.T) {
			code := h.pairingCode("/")
			key := map[string]any{"kty": valid.Kty, "crv": valid.Crv, "x": valid.X, "y": valid.Y}
			switch kind {
			case "missing":
				key = nil
			case "private":
				key["d"] = "never-accept-private-material"
			case "curve":
				key["crv"] = "P-384"
			case "point":
				key["x"] = base64.RawURLEncoding.EncodeToString(make([]byte, 32))
				key["y"] = key["x"]
			case "encoding":
				key["x"] = valid.X + "="
			}
			body, _ := json.Marshal(map[string]any{"code": code.Code, "public_key": key})
			r, b := h.browserDo(req{method: http.MethodPost, path: "/api/v0/pairing/exchange", body: string(body), header: mutationHeaders(h.ownOrigin(), nil)})
			expect(t, r, b, 400, CodeInvalidRequest)
			good, _ := json.Marshal(PairingExchangeRequest{Code: code.Code, PublicKey: valid})
			r, b = h.browserDo(req{method: http.MethodPost, path: "/api/v0/pairing/exchange", body: string(good), header: mutationHeaders(h.ownOrigin(), nil)})
			expect(t, r, b, 200, "")
		})
	}
}

func TestBrowserProofGuardsAndConcurrentSingleUse(t *testing.T) {
	h := newHarness(t)
	key, paired := h.pairBrowserKey()
	body, _ := json.Marshal(SessionProofChallengeRequest{RegistrationID: paired.RegistrationID})
	for _, path := range []string{"/api/v0/pairing/session-proof", "/api/v0/pairing/session-proof/verify"} {
		r, b := h.localDo(req{method: http.MethodPost, path: path, body: string(body)})
		expect(t, r, b, 403, CodeNotServedHere)
		r, b = h.tailnetDo(req{method: http.MethodPost, path: path, body: string(body), header: mutationHeaders("https://"+testTailnetHost, map[string]string{tailscaleLoginHead: testTailnetLogin})})
		expect(t, r, b, 403, CodeNotServedHere)
		pairedOrigin := "http://paired.example:5173"
		token := h.pairOrigin(pairedOrigin)
		r, b = h.browserDo(req{method: http.MethodPost, path: path, body: string(body), header: mutationHeaders(pairedOrigin, map[string]string{"Authorization": "Bearer " + token})})
		expect(t, r, b, 403, CodeOriginRefused)
		r, b = h.browserDo(req{method: http.MethodPost, path: path, body: string(body), header: map[string]string{"Origin": h.ownOrigin()}})
		expect(t, r, b, 403, CodeMutationRefused)
		r, b = h.browserDo(req{method: http.MethodPost, path: path, body: string(body), header: mutationHeaders("", nil)})
		expect(t, r, b, 403, CodeOriginRefused)
	}
	proof := signedProof(t, key, h.ownOrigin(), paired.RegistrationID, h.proofChallenge(paired.RegistrationID))
	var wg sync.WaitGroup
	statuses := make(chan int, 8)
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func() { defer wg.Done(); r, _ := h.submitProof(h.ownOrigin(), proof); statuses <- r.StatusCode }()
	}
	wg.Wait()
	close(statuses)
	success := 0
	for code := range statuses {
		if code == 200 {
			success++
		} else if code != 401 {
			t.Fatalf("concurrent proof status %d", code)
		}
	}
	if success != 1 {
		t.Fatalf("nonce redeemed %d times", success)
	}
	// A proof signed before revocation is refused even when its signature is valid.
	proof = signedProof(t, key, h.ownOrigin(), paired.RegistrationID, h.proofChallenge(paired.RegistrationID))
	h.revokeSessions("")
	r, b := h.submitProof(h.ownOrigin(), proof)
	expect(t, r, b, 401, CodeSessionProofInvalid)
}

func TestBrowserBearerExpiryRecheckedAtTicketAdmission(t *testing.T) {
	h := newHarness(t)
	_, paired := h.pairBrowserKey()
	h.clock.Advance(browserBearerTTL - 10*time.Second)
	r, b := h.browserDo(req{method: http.MethodPost, path: "/api/v0/ws-tickets", body: "{}", header: mutationHeaders(h.ownOrigin(), map[string]string{"Authorization": "Bearer " + paired.Token})})
	expect(t, r, b, 200, "")
	var issued TicketResponse
	if err := json.Unmarshal(b, &issued); err != nil {
		t.Fatal(err)
	}
	ticket := issued.Ticket
	client := sessionClient(paired.RegistrationID)
	stale := caller{listener: ListenerBrowser, auth: "session", origin: h.ownOrigin(), client: client, credential: hashToken(paired.Token)}
	if !h.s.callerLive(stale) {
		t.Fatal("unexpired browser bearer refused")
	}
	h.clock.Advance(10 * time.Second)
	if h.s.callerLive(stale) {
		t.Fatal("expired bearer authorization remained live")
	}
	h.expectBrowserClose(t, "ticket from expired bearer", "?ticket="+ticket, http.Header{"Origin": {h.ownOrigin()}}, CloseUnauthenticated)
}

// sessionClientLive reports whether client, a key from sessionClient, still
// names a session. Keys of other kinds are not sessions and always are.
func (a *authStore) sessionClientLive(client string) bool {
	if !strings.HasPrefix(client, "session:") {
		return true
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	if err := a.reloadSessionsLocked(); err != nil {
		return false
	}
	s, ok := a.sessions[strings.TrimPrefix(client, "session:")]
	return ok && a.now().Before(s.ExpiresAt)
}

// Check the committed synthetic vector independently of signature generation,
// so SDK consumers have a usable raw-r||s interoperability example.
func TestBrowserProofFixtureSignature(t *testing.T) {
	key, err := fixtureBrowserPublicKey().ecdsaKey()
	if err != nil {
		t.Fatal(err)
	}
	sig, err := base64.RawURLEncoding.DecodeString(fixtureBrowserSignature)
	if err != nil {
		t.Fatal(err)
	}
	digest := sha256.Sum256([]byte(BrowserProofMessage("http://127.0.0.1:7861", browserRegistrationID("http://127.0.0.1:7861", fixtureBrowserPublicKey()), "synthetic-nonce", 1790985600000)))
	if !ecdsa.Verify(key, digest[:], new(big.Int).SetBytes(sig[:32]), new(big.Int).SetBytes(sig[32:])) {
		t.Fatal("fixture signature does not match the documented signing message")
	}
}
