package agentlifecycle

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/marcus/sidecar/internal/agentactivity"
)

// assertJSONFixture compares a value against a hand-edited golden.
//
// There is deliberately no -update flag. These fixtures are the wire contract
// for records that hooks write, other processes read, and a future version of
// Sidecar has to keep understanding; a schema change should have to be typed
// out and reviewed, not regenerated by the thing that changed it.
func assertJSONFixture(t *testing.T, path string, value any) {
	t.Helper()
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	got, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if strings.TrimSpace(string(got)) != strings.TrimSpace(string(want)) {
		t.Fatalf("schema drift in %s\n--- got ---\n%s\n--- want ---\n%s", path, got, want)
	}
}

func ptr[T any](v T) *T { return &v }

func contractIdentity() Identity {
	return Identity{
		Host:               "local",
		ServerIncarnation:  "present inode=10 ctime=20 pid=30",
		PaneID:             "%7",
		Provider:           "opencode",
		RunID:              "run-7f3a",
		ProcessGeneration:  "pid=4242 start=1000",
		SessionFingerprint: "sf-9c1d4e2b",
	}
}

// TestLifecycleJSONContracts freezes the four wire schemas the M6 plan defines.
func TestLifecycleJSONContracts(t *testing.T) {
	observed := time.Date(2026, 8, 30, 17, 0, 0, 0, time.UTC)

	assertJSONFixture(t, "testdata/report-state.json", Report{
		SchemaVersion: SchemaVersion,
		ID:            "rpt-01J9",
		Kind:          KindState,
		Identity:      contractIdentity(),
		Source:        "sidecar.opencode.plugin",
		SourceVersion: "1",
		Sequence:      42,
		State:         agentactivity.StateBlocked,
		ObservedAt:    observed,
		Reason:        ReasonPermissionRequest,
		Detail:        "permission requested for tool bash",
	})

	assertJSONFixture(t, "testdata/report-end.json", Report{
		SchemaVersion: SchemaVersion,
		ID:            "rpt-01JA",
		Kind:          KindEnd,
		Identity:      contractIdentity(),
		Source:        "sidecar.opencode.plugin",
		SourceVersion: "1",
		Sequence:      43,
		Outcome:       OutcomeCompleted,
		ObservedAt:    observed.Add(time.Second),
		Reason:        ReasonTurnComplete,
	})

	assertJSONFixture(t, "testdata/explanation.json", Explanation{
		SchemaVersion:     SchemaVersion,
		State:             agentactivity.StateBlocked,
		Authority:         AuthorityLifecycle,
		Tier:              TierFull,
		Freshness:         FreshnessFresh,
		Provider:          "opencode",
		Source:            "sidecar.opencode.plugin",
		SourceVersion:     "1",
		IntegrationStatus: StatusCurrent,
		ScreenState:       agentactivity.StateWorking,
		ScreenEvidence:    "opencode.screen.progress-working",
		ReportState:       agentactivity.StateBlocked,
		ReportKind:        KindState,
		ReportReason:      ReasonPermissionRequest,
		ReportSequence:    42,
		ReportAt:          observed,
		ReportAge:         "2s",
		FreshnessWindow:   "8h0m0s",
		Identity:          contractIdentity(),
		ProcessAlive:      true,
	})

	assertJSONFixture(t, "testdata/report-result.json", ReportResult{
		SchemaVersion: SchemaVersion,
		Accepted:      AcceptedAdvisory,
		Tier:          TierAdvisory,
		TierReason:    ReasonCapabilityUnproved,
		ID:            "rpt-01J9",
		Sequence:      42,
		Identity:      contractIdentity(),
	})

	assertJSONFixture(t, "testdata/error.json", ErrorEnvelope{Error: &Error{
		Code:     ErrStaleSequence,
		Message:  "sequence 41 does not advance past 42 for this source and run",
		Identity: ptr(contractIdentity()),
	}})

	assertJSONFixture(t, "testdata/integration-report.json", IntegrationReport{
		SchemaVersion:         SchemaVersion,
		Provider:              "opencode",
		Source:                "sidecar.opencode.plugin",
		Status:                StatusOutdated,
		BundledVersion:        "2",
		InstalledVersion:      "1",
		ProviderVersion:       "1.18.23",
		ProviderInTestedRange: true,
		EffectiveTier:         TierAdvisory,
		TierReason:            ReasonCapabilityUnproved,
		TargetPaths:           []string{"~/.config/opencode/plugin/sidecar-lifecycle.js"},
		KnownGaps:             []string{"cancellation is untraced"},
		Message:               "run `sidecar agent integration update opencode` to install asset version 2",
	})
}

// TestLifecycleVocabulariesAreFrozen pins every enum this package defines, by
// value and by order.
//
// Order matters as much as membership: these lists are rendered in CLI help, in
// the Configuration surface, and in documentation, and a silent reordering is a
// silent change to all three.
func TestLifecycleVocabulariesAreFrozen(t *testing.T) {
	if SchemaVersion != 1 {
		t.Fatalf("SchemaVersion = %d; bumping it is a deliberate wire change", SchemaVersion)
	}

	if got, want := Kinds(), []Kind{"state", "session", "end", "release"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("kinds = %#v", got)
	}
	if got, want := Outcomes(), []Outcome{"completed", "cancelled", "failed", "unknown"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("outcomes = %#v", got)
	}
	if got, want := Tiers(), []Tier{"full", "advisory", "session-identity", "screen-fallback"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("tiers = %#v", got)
	}
	if got, want := Authorities(), []Authority{"lifecycle", "screen"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("authorities = %#v", got)
	}
	if got, want := Freshnesses(), []Freshness{"fresh", "stale", "released", "none"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("freshnesses = %#v", got)
	}
	if got, want := EvidenceQualities(), []EvidenceQuality{"real-trace", "docs-only", "none"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("evidence qualities = %#v", got)
	}
	if got, want := Acceptances(), []Acceptance{"accepted_authoritative", "accepted_advisory", "accepted_duplicate"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("acceptances = %#v", got)
	}
	if got, want := IntegrationStatuses(), []IntegrationStatus{
		"provider-missing", "not-installed", "current", "outdated", "needs-repair", "unsupported",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("integration statuses = %#v", got)
	}
	if got, want := Transitions(), []Transition{
		"work_start", "tool_use", "blocked_on_request", "unblocked", "turn_complete",
		"cancelled", "session_identity", "subagent", "process_exit",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("transitions = %#v", got)
	}
	if got, want := FullLifecycleTransitions(), []Transition{
		"work_start", "blocked_on_request", "unblocked", "turn_complete",
		"cancelled", "session_identity", "process_exit",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("full lifecycle transitions = %#v", got)
	}
	if got, want := Reasons(), []ReasonCode{
		"turn_start", "tool_use", "permission_request", "question", "permission_resolved",
		"turn_complete", "cancelled", "session_start", "session_change", "subagent_start",
		"subagent_stop", "compaction", "process_exit", "integration_removed",
		"provider_error", "unspecified",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("reason codes = %#v", got)
	}
	if got, want := ErrorCodes(), []ErrorCode{
		"lifecycle_invalid_context", "lifecycle_invalid_report", "lifecycle_stale_sequence",
		"lifecycle_run_mismatch", "lifecycle_unsupported_source", "lifecycle_store_failed",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("error codes = %#v", got)
	}
	if got, want := FallbackReasons(), []FallbackReason{
		"no_integration", "provider_missing", "integration_unsupported",
		"integration_needs_repair", "integration_outdated", "integration_removed",
		"capability_unproved", "provider_version_unproved", "tier_advisory",
		"tier_session_identity",
		"no_report", "report_stale", "authority_released", "run_ended",
		"run_mismatch", "process_generation_mismatch", "session_mismatch",
		"pane_mismatch", "server_incarnation_changed", "host_mismatch",
		"provider_mismatch", "source_mismatch", "process_exited",
		"store_unavailable", "invalid_reports",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("fallback reasons = %#v", got)
	}
}

// TestReportStatesAreASubsetOfActivityStates keeps the lifecycle lane
// vocabulary tied to the one the rest of Sidecar renders, and proves the
// deliberate omission of "unknown".
func TestReportStatesAreASubsetOfActivityStates(t *testing.T) {
	want := []agentactivity.State{
		agentactivity.StateWorking, agentactivity.StateBlocked, agentactivity.StateIdle,
	}
	if !reflect.DeepEqual(ReportStates(), want) {
		t.Fatalf("report states = %#v", ReportStates())
	}
	for _, s := range ReportStates() {
		if s == agentactivity.StateUnknown {
			t.Fatal("a report may never assert the unknown state")
		}
	}
}

// TestFreshnessPolicyIsPinned freezes the provisional Phase A windows.
//
// These are expected to change once Phase D measures real per-provider event
// cadence. The point of pinning them is that the change arrives as a reviewed
// edit to this list rather than as a quiet constant tweak, because widening the
// working window is exactly how a crashed agent would come to look busy for
// half an hour.
func TestFreshnessPolicyIsPinned(t *testing.T) {
	p := DefaultFreshnessPolicy()
	if p.Working != 30*time.Minute {
		t.Fatalf("working window = %s", p.Working)
	}
	if p.Blocked != 8*time.Hour {
		t.Fatalf("blocked window = %s", p.Blocked)
	}
	if p.Idle != 8*time.Hour {
		t.Fatalf("idle window = %s", p.Idle)
	}
	// An unknown lane must expire soonest, never linger longest.
	if p.For(agentactivity.StateUnknown) != p.Working {
		t.Fatalf("unknown lane window = %s, want the working window", p.For(agentactivity.StateUnknown))
	}
}

// TestReportKeyScopesSequenceCorrectly proves the sequence scope is exactly the
// tuple the plan names, so two sources or two runs in one pane cannot collide.
func TestReportKeyScopesSequenceCorrectly(t *testing.T) {
	base := Report{Identity: contractIdentity(), Source: "sidecar.opencode.plugin"}
	if got, want := base.Key(), (Key{
		ServerIncarnation: "present inode=10 ctime=20 pid=30",
		PaneID:            "%7",
		Source:            "sidecar.opencode.plugin",
		RunID:             "run-7f3a",
	}); got != want {
		t.Fatalf("key = %#v", got)
	}

	otherSource := base
	otherSource.Source = "custom.reporter"
	if base.Key() == otherSource.Key() {
		t.Fatal("two sources in one pane must not share a sequence scope")
	}
	otherRun := base
	otherRun.Identity.RunID = "run-next"
	if base.Key() == otherRun.Key() {
		t.Fatal("two runs in one pane must not share a sequence scope")
	}
	// The pane's host and provider are intentionally NOT part of the scope:
	// they are validated as identity, and folding them in would let a provider
	// rename silently reset a sequence.
	otherHost := base
	otherHost.Identity.Host = "elsewhere"
	if base.Key() != otherHost.Key() {
		t.Fatal("host must not participate in the sequence scope")
	}
}
