package agentintegration

import (
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"sync"
)

// Everything under upstream/ is a byte-for-byte copy of a file from Herdr's
// src/integration/assets, vendored by internal/tools/herdrsync and never edited
// by hand. TestVendoredIntegrationAssetsMatchLock hashes each one against
// upstream.lock.json, so an edit fails CI the same way it does for the vendored
// detection manifests.
//
// These files are reference material, not shipped assets: nothing installs them
// and no runtime path reads them. They exist so that re-porting a provider is a
// review of a diff against the upstream a Sidecar asset was written from,
// rather than a fresh reading of the file. Sidecar's own assets live under
// assets/, and PortedFromRecords says which upstream version each was written
// against.
//
// The all: prefix is load-bearing. Without it embed drops every file whose name
// begins with "_" or ".", which silently loses hermes/__init__.py -- the one
// file in the tree with such a name, and the whole of that provider's asset.
//
//go:embed all:upstream
var upstreamAssets embed.FS

//go:embed upstream.lock.json
var upstreamLockBytes []byte

// UpstreamLockSchemaVersion is the shape version of upstream.lock.json. Bump it
// when a field changes meaning, so a stale lock fails loudly.
const UpstreamLockSchemaVersion = 1

// UpstreamGeneratedNotice is the Origin recorded for upstream/NOTICE, which
// Sidecar writes rather than copies.
const UpstreamGeneratedNotice = "generated by internal/tools/herdrsync"

// UpstreamLock pins exactly which Herdr integration-asset bytes are vendored
// and where they came from.
type UpstreamLock struct {
	SchemaVersion int                `json:"schema_version"`
	GeneratedAt   string             `json:"generated_at"`
	Herdr         UpstreamLockSource `json:"herdr"`
	// Providers is one entry per directory under src/integration/assets, sorted
	// by agent id.
	Providers []UpstreamProvider `json:"providers"`
	// Files pins everything vendored that does not belong to a provider: the
	// shared asset test at the top of the assets directory, the upstream
	// LICENSE, and the generated NOTICE.
	Files []UpstreamFile `json:"files"`
	Notes []string       `json:"notes,omitempty"`
}

// UpstreamLockSource pins the Herdr source the assets were read from.
type UpstreamLockSource struct {
	Repository string `json:"repository"`
	Ref        string `json:"ref"`
	Commit     string `json:"commit,omitempty"`
	SourceDir  string `json:"source_dir,omitempty"`
	// AssetsDir is the upstream directory the tree mirrors.
	AssetsDir string `json:"assets_dir"`
}

// UpstreamProvider is one provider's vendored integration assets.
type UpstreamProvider struct {
	// ID is the Herdr agent id, which differs from Directory where Herdr's
	// directory name and its agent id disagree (antigravity_cli is agy).
	ID string `json:"id"`
	// Directory is the directory name under src/integration/assets, preserved
	// as the vendored subdirectory name.
	Directory string `json:"directory"`
	// Version is the HERDR_INTEGRATION_VERSION every file in the directory
	// agrees on, or 0 where none of them declares one.
	Version int            `json:"version"`
	Files   []UpstreamFile `json:"files"`
}

// UpstreamFile pins one vendored file.
type UpstreamFile struct {
	// Path is relative to internal/agentintegration, e.g.
	// "upstream/claude/herdr-agent-state.sh".
	Path string `json:"path"`
	// Origin is the upstream path the bytes came from, or a description of what
	// generated them where Sidecar writes the file itself.
	Origin string `json:"origin"`
	SHA256 string `json:"sha256"`
	Bytes  int    `json:"bytes"`
	// Version is the HERDR_INTEGRATION_VERSION this file declares, or 0 when it
	// declares none. A test file carries no version; a hook asset does.
	Version int `json:"version,omitempty"`
}

var (
	upstreamOnce sync.Once
	upstreamSub  fs.FS
	upstreamErr  error

	upstreamLockOnce  sync.Once
	upstreamLockValue *UpstreamLock
	upstreamLockErr   error
)

// UpstreamAssets returns the vendored Herdr integration assets as a filesystem
// rooted at the upstream directory, so a caller opens "claude/herdr-agent-state.sh"
// rather than "upstream/claude/herdr-agent-state.sh".
//
// The embed itself costs nothing at init; only this sub-filesystem is built,
// and only on first use, per the startup-latency rule.
func UpstreamAssets() (fs.FS, error) {
	upstreamOnce.Do(func() {
		upstreamSub, upstreamErr = fs.Sub(upstreamAssets, "upstream")
	})
	return upstreamSub, upstreamErr
}

// UpstreamAssetBytes reads one vendored file by its path relative to upstream/.
func UpstreamAssetBytes(name string) ([]byte, error) {
	dir, err := UpstreamAssets()
	if err != nil {
		return nil, err
	}
	return fs.ReadFile(dir, name)
}

// LoadUpstreamLock returns the parsed lock. It is decoded once, on first use,
// and shared; callers must not mutate the result.
func LoadUpstreamLock() (*UpstreamLock, error) {
	upstreamLockOnce.Do(func() {
		var lock UpstreamLock
		if err := json.Unmarshal(upstreamLockBytes, &lock); err != nil {
			upstreamLockErr = fmt.Errorf("decode upstream.lock.json: %w", err)
			return
		}
		if lock.SchemaVersion != UpstreamLockSchemaVersion {
			upstreamLockErr = fmt.Errorf("upstream.lock.json schema_version is %d, want %d",
				lock.SchemaVersion, UpstreamLockSchemaVersion)
			return
		}
		upstreamLockValue = &lock
	})
	return upstreamLockValue, upstreamLockErr
}

// UpstreamLockJSON returns the raw upstream.lock.json bytes.
func UpstreamLockJSON() []byte { return upstreamLockBytes }

// Provider returns the lock entry for a Herdr agent id.
func (l *UpstreamLock) Provider(id string) (UpstreamProvider, bool) {
	for _, provider := range l.Providers {
		if provider.ID == id {
			return provider, true
		}
	}
	return UpstreamProvider{}, false
}

// File returns the lock entry for a vendored non-provider file path, such as
// "upstream/LICENSE".
func (l *UpstreamLock) File(path string) (UpstreamFile, bool) {
	for _, file := range l.Files {
		if file.Path == path {
			return file, true
		}
	}
	return UpstreamFile{}, false
}
